### PR TITLE
Changing RFCXXXX string to OPAQUEv1-

### PR DESCRIPTION
**Pull request by kevinlewi**
Based on Scott Fluhrer's mailing list comments:

"At one point, the draft uses “RFCXXXX” as a protocol identifier in the preamble; is that expected to be replaced by the assigned RFC number?  If so, I would suggest you add instructions to the RFC editors to that effect."

### CODE REVIEW

**Review by chris-wood — COMMENTED** [review]
Alternatively, we could just use `"OPAQUEv1"` or whatever as the string, and avoid the RFC number dependency altogether? That would let us generate test vectors right now.

**Comment by kevinlewi** [comment]
Yeah that might be nicer. I see that VOPRF does "OPRFv1-" as the context string -- perhaps we can just follow suit?

**Comment by chris-wood** [comment]
> Yeah that might be nicer. I see that VOPRF does "OPRFv1-" as the context string -- perhaps we can just follow suit?

Yep, that's my suggestion.

**Comment by kevinlewi** [comment]
Updated the string from "RFCXXXX" to "OPAQUEv1-". Also re-ran test vector generation

**Review by chris-wood — APPROVED** [review]

**Pull request merged**
