### PR TITLE
Add back alternate AKE sketches

### LINKED ISSUE #128: HMQV and SIGMA to an Appendix
I want the HMQV and SIGMA specification to appear in an appendix. It serves as illustration and guidance for these and other instantiations.  Note that there is text referring to these protocols (e.g., introduction) that needs to be updated.

### PR DESCRIPTION
**Pull request by chris-wood**
Also, nail down the MHF parameters. We don't currently allow them to be negotiated *in* the protocol. (The wrapper protocol may choose to allow negotiation, but that negotiation would yield a different configuration.)

Closes #128 and #69.

cc @hugokraw

### CODE REVIEW

**Comment by kevinlewi** [comment]
Change overall looks good to me. One nit: Perhaps preface the titles of the last few sections with "Appendix: Test Vectors" and "Appendix: Alternate AKE instantiations", just to make it extra clear?

**Comment by chris-wood** [comment]
These are already rendered in the appendix:

```
   Appendix B.  Alternate AKE instantiations
     B.1.  HMQV Instantiation Sketch
     B.2.  SIGMA-I Instantiation Sketch
```

Probably adding "Appendix" to the section headers would be redundant?

**Comment by kevinlewi** [comment]
> These are already rendered in the appendix:
> 
> ```
>    Appendix B.  Alternate AKE instantiations
>      B.1.  HMQV Instantiation Sketch
>      B.2.  SIGMA-I Instantiation Sketch
> ```
> 
> Probably adding "Appendix" to the section headers would be redundant?

Oops, didn't realize that. Great!

**Comment by kevinlewi** [comment]
Test vectors look good!

**Review by kevinlewi — APPROVED** [review]

**Comment by hugokraw** [comment]
I see no point in adding SIGMA to the appendix the way it is now. If you put a sketch of it in the appendix then let's put a sketch of it, not just one sentence. The only substantial difference with the description of 3DH and HMQV is the signature. The rest follows the same pattern as 3DH and HMQV.  I believe that this description will be useful and since we do not provide test vectors then it does not have an extra cost.

**Pull request merged**
