### PR TITLE
Clarifying the use of multiple client seeds

### PR DESCRIPTION
**Pull request by kevinlewi**
Addresses #426

### CODE REVIEW

**Comment by daxpedda** [comment]
If the OPRF seed has to be the same to prevent client enumeration, I think it should be noted here.

**Review by chris-wood — APPROVED** [review]
This LGTM. I'm also OK with folding in @daxpedda's additional suggestion. Please feel free to merge as you see fit.

**Comment by kevinlewi** [comment]
Updated the sentence to say:

The server can also opt to use different seeds for each client,
so long as they are maintained across the registration and online AKE stages, and
kept consistent for each client (since an inconsistent mapping of clients to seeds
could leak information as described in {{preventing-client-enumeration}}).

Hope that works!

**Comment by daxpedda** [comment]
> (since an inconsistent mapping of clients to seeds
> could leak information as described in {{preventing-client-enumeration}})

Wouldn't that require consistent mapping between pre- and post-registered clients?
E.g. unregistered client X requires to have the same seed as registered client X, otherwise an attacker could notice the difference and determine that client X was not registered but is registered now.

The only way I see this could be done is by deriving a seed from the client identifier/identity, which seems rather problematic to me.

**Comment by daxpedda** [comment]
To clarify though: I think the change LGTM, I was just worried about how implementers could interpret this.

**Comment by kevinlewi** [comment]
> > (since an inconsistent mapping of clients to seeds
> > could leak information as described in {{preventing-client-enumeration}})
> 
> Wouldn't that require consistent mapping between pre- and post-registered clients? E.g. unregistered client X requires to have the same seed as registered client X, otherwise an attacker could notice the difference and determine that client X was not registered but is registered now.
> 
> The only way I see this could be done is by deriving a seed from the client identifier/identity, which seems rather problematic to me.

Yes, this requires a consistent mapping between pre and post registered clients. The situation I am thinking of is the following. Let's say the server sets the policy:
- if the client identity starts with an A, then always use seed X for registration login
- if the client identity starts with a B, then always use seed Y for registration and login
- ... and so on

The purpose of the sentence "The server can also opt to use different seeds for each client" is to indicate that it is indeed OK to set this kind of policy. This is not exactly deriving a seed dependent on the client identity, but choosing a seed based on the client identity, which we don't view as problematic.

So I guess my main question is: is the language clear enough to convey that this is what we mean, or is it just causing unnecessary confusion (and maybe we should get rid of the suggestion altogether)?

**Comment by daxpedda** [comment]
> So I guess my main question is: is the language clear enough to convey that this is what we mean, or is it just causing unnecessary confusion (and maybe we should get rid of the suggestion altogether)?

I believe it is clear enough.

**Pull request merged**
