### PR TITLE
Return client pk in Recovery functions

### LINKED ISSUE #384: Return values of the Recover and RecoverCredentials functions
The _ClientFinish_ function (Section 6.2.3) needs the _client_public_key_ if the _client_identity_ is empty. However, the _client_public_key_ is calculated in the _Recover_ function (Section 4.1.3). 
Would it therefore make sense that both the _Recover_ function and the _RecoverCredentials_ function (Section 6.3.2.3) return the _client_public_key_ so that it can also be used for the _AuthClientFinalize_ function (_client_identity_ = _client_public_key_ if _client_identity_ is empty)?

### PR DESCRIPTION
**Pull request by bytemare**
Closes #384.

### CODE REVIEW

**Comment by bytemare** [comment]
At this point I'm wondering whether we should not simply bubble up the `cleartext_creds` from `Recover()` up to `ClientFinish()` and feed it to `AuthClientFinalize()` to avoid input arguments comments like

> the optional encoded xyyz identity, which is set to xyz_public_key if not specified.

**Review by chris-wood — COMMENTED** [review]
Should we also update the reference implementation to match?

**Comment by chris-wood** [comment]
> At this point I'm wondering whether we should not simply bubble up the cleartext_creds from Recover() up to ClientFinish() and feed it to AuthClientFinalize() to avoid input arguments comments like

Maybe! Would you be willing to draft a change so we can see what this looks like?

**Comment by bytemare** [comment]
@caw done :)

**Review by chris-wood — APPROVED** [review]

**Pull request merged**
